/**
 * @seashorelab/tool - Types
 *
 * Type definitions for tools
 */

import type { z, ZodSchema } from 'zod';

/**
 * Tool execution context
 */
export interface ToolContext {
  /** Unique execution ID */
  executionId: string;

  /** Thread ID if within an agent conversation */
  threadId?: string;

  /** User ID if available */
  userId?: string;

  /** Abort signal for cancellation */
  signal?: AbortSignal;

  /** Custom metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Tool execution result
 */
export interface ToolResult<T> {
  /** Whether execution succeeded */
  success: boolean;

  /** Result data (if successful) */
  data?: T;

  /** Error message (if failed) */
  error?: string;

  /** Execution duration in milliseconds */
  durationMs: number;

  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Tool configuration
 */
export interface ToolConfig<TInput extends ZodSchema, TOutput> {
  /** Tool name (unique identifier) */
  name: string;

  /** Tool description (LLM uses this to decide when to call) */
  description: string;

  /** Input parameter schema (Zod) */
  inputSchema: TInput;

  /** Execution function */
  execute: (input: z.infer<TInput>, context: ToolContext) => Promise<TOutput>;

  /** Whether user approval is required */
  needsApproval?: boolean;

  /** Execution timeout in milliseconds */
  timeout?: number;

  /** Retry configuration */
  retry?: RetryConfig;
}

/**
 * Retry configuration
 */
export interface RetryConfig {
  /** Maximum retry attempts */
  maxAttempts: number;

  /** Delay between retries in milliseconds */
  delay: number;

  /** Backoff multiplier (default: 2) */
  backoffMultiplier?: number;
}

/**
 * Tool interface
 */
export interface Tool<TInput, TOutput> {
  /** Tool name */
  name: string;

  /** Tool description */
  description: string;

  /** JSON Schema for LLM function calling */
  jsonSchema: JsonSchema;

  /** Whether user approval is required */
  needsApproval: boolean;

  /** Execute the tool */
  execute(input: TInput, context?: Partial<ToolContext>): Promise<ToolResult<TOutput>>;

  /** Validate input */
  validate(input: unknown): input is TInput;

  /** Parse and validate input (throws on invalid) */
  parse(input: unknown): TInput;
}

/**
 * JSON Schema type enumeration
 */
export type JsonSchemaType =
  | 'object'
  | 'array'
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'null';

/**
 * JSON Schema representation
 *
 * Supports all standard JSON Schema properties generated by Zod 4's toJSONSchema()
 */
export interface JsonSchema {
  /** JSON Schema version identifier */
  $schema?: string;

  /** Type (supports multiple JSON Schema types) */
  type?: JsonSchemaType;

  /** Object property definitions */
  properties?: Record<string, JsonSchemaProperty>;

  /** Required field list */
  required?: string[];

  /** Whether additional properties are allowed */
  additionalProperties?: boolean;

  /** Array item type */
  items?: JsonSchemaProperty;

  /** Enum values list */
  enum?: unknown[];

  /** Constant value (literal types) */
  const?: unknown;

  /** Union type (oneOf) */
  oneOf?: JsonSchemaProperty[];

  /** Union type (anyOf) */
  anyOf?: JsonSchemaProperty[];

  /** Numeric constraints */
  minimum?: number;
  maximum?: number;

  /** String constraints */
  minLength?: number;
  maxLength?: number;

  /** Array constraints */
  minItems?: number;
  maxItems?: number;

  /** String format (uuid, email, uri, etc.) */
  format?: string;

  /** Default value */
  default?: unknown;

  /** Description */
  description?: string;
}

/**
 * JSON Schema property definition
 *
 * Supports nested objects, arrays, union types, and other complex structures
 */
export interface JsonSchemaProperty {
  /** Type */
  type?: string;

  /** Description */
  description?: string;

  /** Enum values list */
  enum?: unknown[];

  /** Constant value (literal types) */
  const?: unknown;

  /** Array item type */
  items?: JsonSchemaProperty;

  /** Nested object properties */
  properties?: Record<string, JsonSchemaProperty>;

  /** Nested object required fields */
  required?: string[];

  /** Union type (oneOf) */
  oneOf?: JsonSchemaProperty[];

  /** Union type (anyOf) */
  anyOf?: JsonSchemaProperty[];

  /** Numeric constraints */
  minimum?: number;
  maximum?: number;

  /** String constraints */
  minLength?: number;
  maxLength?: number;

  /** Array constraints */
  minItems?: number;
  maxItems?: number;

  /** String format (uuid, email, uri, etc.) */
  format?: string;

  /** Default value */
  default?: unknown;

  /** Whether additional properties are allowed (nested objects) */
  additionalProperties?: boolean;
}

/**
 * Tool call from LLM
 */
export interface ToolCallRequest {
  id: string;
  name: string;
  arguments: string; // JSON string
}

/**
 * Tool call response
 */
export interface ToolCallResponse {
  id: string;
  name: string;
  result: ToolResult<unknown>;
}
